apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
  # Basicamente o template do POD
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: jhousyfran/hello-go:v4
          # === CARREGANDO TODAS AS VARIAVEIS DO CONFIGMAP
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #     # === PASSANDO AS VARIAVEIS EXPLICITAMENTES COM VALORES
          #     # - name: NAME
          #     #   value: 'Jhousyfran Costa'
          #     # - name: AGE
          #     #   value: '23'

          #     # === SETANDO AS VARIAVEIS COM VALORES DO CONFIGMAP
          #     - name: NAME
          #       valueFrom:
          #         configMapKeyRef:
          #           name: goserver-env
          #           key: NAME
          #     - name: AGE
          #       valueFrom:
          #         configMapKeyRef:
          #           name: goserver-env
          #           key: AGE